### ISSUE TITLE
Suppress Light Switch

### ISSUE THREAD

**Issue by applemanj** [oogje/homebridge-i6-bigAssFans#24]
I'd propose an enhancement to be able to suppress the light function for each fan by adding a line to the configuration. (i.e. hide the light switch even if it's discovered to be available for the specific model fan).

**Comment by oogje** [comment]
Sure, why not.  Will post here when there's a beta to try out.

**Comment by oogje** [comment]
Am starting to look into this.  I don't know any way to "hide" the light switch.  But I can avoid creating it to begin with, or I can disable it by ignoring the user inputs.  My first thought was to not create it but that will mean you cannot use HomeKit scenes or automations that involve the light.  Is that what you had in mind, to treat the fan as if it has no lights as far as HomeKit is concerned?

**Comment by applemanj** [comment]
The use case was essentially that I'd like to be able to say, "Turn on the lights in the primary bedroom," and for all of my nice non-BAF lights to come on while the crappy little light built into the Haku fan would stay hidden.  So disable/hide/ignore at discovery I suspect all works out to be about the same outcome.  I suppose maybe if it were discovered as two separate devices it could be hidden from Homekit, but because it discovers as all one unit I can't enjoy the fan being part of the primary bedroom while ignoring the crappy light. Thanks again for all your help with this, certainly not a show-stopper but a minor annoyance for my use case.

**Comment by oogje** [comment]
Okay, I think I understand what you want.  Thanks.

**Comment by oogje** [comment]
Hello. ` homebridge-i6-bigassfans@0.5.4-beta5` attempts to implement your idea.  Setting `"noLights": true` in the config should keep your lights away from HomeKit.

**Comment by applemanj** [comment]
12/28/2022, 6:01:09 PM] TypeError: Cannot read properties of undefined (reading 'removeCharacteristic')
    at Array.productType (/homebridge/node_modules/homebridge-i6-bigassfans/src/platformAccessory.ts:1079:31)
    at /homebridge/node_modules/homebridge-i6-bigassfans/src/platformAccessory.ts:921:15
    at Array.forEach (<anonymous>)
    at onData (/homebridge/node_modules/homebridge-i6-bigassfans/src/platformAccessory.ts:919:14)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-i6-bigassfans/src/platformAccessory.ts:843:5)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[12/28/2022, 6:01:09 PM] [BigAssFans-i6] Office Fan - downlight detected
[12/28/2022, 6:01:09 PM] [BigAssFans-i6] Office Fan - no uplight detected
[12/28/2022, 6:01:09 PM] [BigAssFans-i6] Primary Bedroom Fan - current temperature out of range: 1000, assuming no temperature sensor for model "Haiku L Series"
[12/28/2022, 6:01:09 PM] [BigAssFans-i6] Primary Bedroom Fan - current relative humidity out of range: 1000, assuming no humidity sensor for model "Haiku L Series"
[12/28/2022, 6:01:09 PM] Got SIGTERM, shutting down Homebridge...



Config:

            "fans": [
                {
                    "name": "Primary Bedroom Fan",
                    "ip": "192.168.1.119",
                    "mac": "20:f8:5e:3e:b1:bb",
                    "fanModel": "Haiku L Series",
                    "showWhooshSwitch": false,
                    "showFanAutoSwitch": false,
                    "showLightAutoSwitch": false,
                    "showDimToWarmSwitch": false,
                    "showEcoModeSwitch": false,
                    "disableDirectionControl": true,
                    "noLights": true
                },

**Comment by oogje** [comment]
New beta - `homebridge-i6-bigassfans@0.5.4-beta6`.

**Comment by applemanj** [comment]
It works!!! Thank you!!!
